# Generated by Django 2.1 on 2018-08-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_auto_20180827_1742'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dialogues',
        ),
        migrations.AddField(
            model_name='profile',
            name='dialogues',
            field=models.ManyToManyField(to='messenger.Chat'),
        ),
    ]
