# Generated by Django 2.1 on 2018-09-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180827_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='about',
            field=models.CharField(choices=[('Like', 'Like'), ('Repost', 'Repost'), ('Subscribe', 'Subscribe'), ('Another', 'Another'), ('Comment', 'Comment')], default='Another', max_length=30),
        ),
    ]
