# Generated by Django 2.1 on 2018-09-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180904_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='about',
            field=models.CharField(choices=[('Like', 'Like'), ('Repost', 'Repost'), ('Subscribe', 'Subscribe'), ('Another', 'Another'), ('PostComment', 'PostComment'), ('CommentComment', 'CommentComment')], default='Another', max_length=30),
        ),
    ]
