# Generated by Django 2.1 on 2018-09-08 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20180906_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admittance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('on_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
