# Generated by Django 2.1 on 2018-09-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180908_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admittance',
            name='allowed',
        ),
    ]
