# Generated by Django 2.1 on 2018-09-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_admittance_allowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admittance',
            old_name='for_user',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='admittance',
            name='on_page',
        ),
    ]
