# Generated by Django 2.1 on 2018-09-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20180909_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admittance',
            old_name='member',
            new_name='for_user',
        ),
    ]
