# Generated by Django 2.1 on 2018-08-27 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20180826_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 17, 42, 10, 581097)),
        ),
    ]
