# Generated by Django 2.1 on 2018-08-27 13:10

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0005_auto_20180827_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 18, 10, 18, 898312)),
        ),
        migrations.RemoveField(
            model_name='message',
            name='who_read',
        ),
        migrations.AddField(
            model_name='message',
            name='who_read',
            field=models.ManyToManyField(related_name='read_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
