# Generated by Django 2.1 on 2018-08-29 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_auto_20180829_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 17, 31, 52, 146609)),
        ),
    ]
