# Generated by Django 2.1 on 2018-08-30 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_auto_20180829_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 30, 17, 24, 13, 551424)),
        ),
    ]
