# Generated by Django 2.1 on 2018-08-30 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_auto_20180830_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 30, 17, 30, 6, 640837)),
        ),
    ]
