# Generated by Django 2.1 on 2018-09-03 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0013_auto_20180830_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 3, 17, 59, 7, 497530)),
        ),
    ]
