# Generated by Django 2.1 on 2018-09-04 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0019_auto_20180904_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 20, 44, 9, 891872)),
        ),
    ]
