# Generated by Django 2.1 on 2018-09-05 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0026_auto_20180905_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='message',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='reader',
        ),
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 15, 48, 35, 106885)),
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
