# Generated by Django 2.1 on 2018-09-06 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0027_auto_20180905_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 13, 44, 46, 573561)),
        ),
    ]
