# Generated by Django 2.1 on 2018-09-06 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0028_auto_20180906_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 14, 4, 31, 311590)),
        ),
    ]
