# Generated by Django 2.1 on 2018-09-06 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0030_auto_20180906_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 18, 48, 52, 192031)),
        ),
        migrations.AddField(
            model_name='imagemessage',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.Message'),
        ),
    ]
