# Generated by Django 2.1 on 2018-09-06 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0033_auto_20180906_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 19, 59, 15, 33595)),
        ),
    ]
