# Generated by Django 2.1 on 2018-09-07 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0034_auto_20180906_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 18, 40, 59, 4912)),
        ),
    ]
