# Generated by Django 2.1 on 2018-09-08 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0037_auto_20180908_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 8, 21, 10, 52, 89370)),
        ),
    ]
