# Generated by Django 2.1 on 2018-09-09 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0039_auto_20180908_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 14, 32, 14, 372440)),
        ),
    ]
