# Generated by Django 2.1 on 2018-09-09 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0040_auto_20180909_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 21, 50, 46, 884236)),
        ),
    ]
