# Generated by Django 2.1 on 2018-09-09 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0041_auto_20180909_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 22, 4, 2, 51561)),
        ),
    ]
