# Generated by Django 2.1 on 2018-09-09 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0044_auto_20180909_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 22, 6, 5, 466031)),
        ),
    ]
