# Generated by Django 2.1 on 2018-09-13 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0045_auto_20180909_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 12, 28, 8, 591071)),
        ),
    ]
