# Generated by Django 2.1 on 2018-09-13 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0046_auto_20180913_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 14, 26, 41, 770468)),
        ),
    ]
