# Generated by Django 2.1 on 2018-09-19 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0047_auto_20180913_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 19, 30, 6, 209592)),
        ),
    ]
