# Generated by Django 2.1 on 2018-09-20 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0048_auto_20180919_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 20, 13, 27, 35, 29105)),
        ),
    ]
