# Generated by Django 2.1 on 2018-09-29 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0050_auto_20180928_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 22, 19, 34, 545160)),
        ),
    ]
